<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'org\\bovigo\\vfs\\' => array($vendorDir . '/mikey179/vfsStream/src/main/php'),
    'TYPO3\\TypoScript' => array($baseDir . '/Packages/Application/TYPO3.TypoScript/Classes'),
    'TYPO3\\Twitter\\Bootstrap' => array($baseDir . '/Packages/Application/TYPO3.Twitter.Bootstrap/Classes'),
    'TYPO3\\TYPO3CR' => array($baseDir . '/Packages/Application/TYPO3.TYPO3CR/Classes'),
    'TYPO3\\Setup' => array($baseDir . '/Packages/Application/TYPO3.Setup/Classes'),
    'TYPO3\\Party' => array($baseDir . '/Packages/Framework/TYPO3.Party/Classes'),
    'TYPO3\\Neos\\NodeTypes' => array($baseDir . '/Packages/Application/TYPO3.Neos.NodeTypes/Classes'),
    'TYPO3\\Neos\\Kickstarter' => array($baseDir . '/Packages/Application/TYPO3.Neos.Kickstarter/Classes'),
    'TYPO3\\NeosDemoTypo3Org' => array($baseDir . '/Packages/Sites/TYPO3.NeosDemoTypo3Org/Classes'),
    'TYPO3\\Neos' => array($baseDir . '/Packages/Application/TYPO3.Neos/Classes'),
    'TYPO3\\Media' => array($baseDir . '/Packages/Application/TYPO3.Media/Classes'),
    'TYPO3\\Kickstart' => array($baseDir . '/Packages/Framework/TYPO3.Kickstart/Classes'),
    'TYPO3\\Imagine' => array($baseDir . '/Packages/Application/TYPO3.Imagine/Classes'),
    'TYPO3\\Form' => array($baseDir . '/Packages/Application/TYPO3.Form/Classes'),
    'TYPO3\\Fluid' => array($baseDir . '/Packages/Framework/TYPO3.Fluid/Classes'),
    'TYPO3\\Flow' => array($baseDir . '/Packages/Framework/TYPO3.Flow/Classes'),
    'TYPO3\\ExtJS' => array($baseDir . '/Packages/Application/TYPO3.ExtJS/Classes'),
    'TYPO3\\Eel' => array($baseDir . '/Packages/Framework/TYPO3.Eel/Classes'),
    'TYPO3\\DocTools' => array($baseDir . '/Packages/Application/TYPO3.DocTools/Classes'),
    'Symfony\\Component\\Yaml' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\DomCrawler\\' => array($vendorDir . '/symfony/dom-crawler'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'Flowpack\\Behat' => array($baseDir . '/Packages/Application/Flowpack.Behat/Classes'),
    'Doctrine\\ORM' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DBAL\\Migrations' => array($vendorDir . '/doctrine/migrations/lib'),
    'Doctrine\\DBAL' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Doctrine\\Common\\' => array($vendorDir . '/doctrine/common/lib'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src'),
);
